### ISSUE TITLE
[Bug]: Laravel 10 issue. Undefinited Method CockroachDbConnection::resetTotalQueryDuration

### ISSUE THREAD

**Issue by fresent** [ylsideas/cockroachdb-laravel#31]
### What happened?

The code was works fine on Laravel 8, and having issue since upgrade to Laravel 10.

It seems bunch of new static methods have been introduced in 
laravel\framework\src\illuminate\Support\Facades\DB.php

Which are being pulled into 
laravel\framework\src\illuminate\Queue\QueueServiceProvider.php

And as these are not available in this library, calls are failing.
Current stacktrace of failure is.

```
[2024-02-02 05:55:12] production.ERROR: Call to undefined method YlsIdeas\CockroachDb\CockroachDbConnection::resetTotalQueryDuration() {"exception":"[object] (Error(code: 0): Call to undefined method YlsIdeas\\CockroachDb\\CockroachDbConnection::resetTotalQueryDuration() at /masked-home-path/application/vendor/laravel/framework/src/Illuminate/Queue/QueueServiceProvider.php:209)
[stacktrace]
#0 /masked-home-path/application/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(156): Illuminate\\Queue\\QueueServiceProvider->Illuminate\\Queue\\{closure}()
#1 /masked-home-path/application/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(138): Illuminate\\Queue\\Worker->daemon()
#2 /masked-home-path/application/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(121): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#3 /masked-home-path/application/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#4 /masked-home-path/application/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#5 /masked-home-path/application/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#6 /masked-home-path/application/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#7 /masked-home-path/application/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#8 /masked-home-path/application/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
#9 /masked-home-path/application/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#10 /masked-home-path/application/vendor/laravel/framework/src/Illuminate/Console/Command.php(181): Symfony\\Component\\Console\\Command\\Command->run()
#11 /masked-home-path/application/vendor/symfony/console/Application.php(1096): Illuminate\\Console\\Command->run()
#12 /masked-home-path/application/vendor/symfony/console/Application.php(324): Symfony\\Component\\Console\\Application->doRunCommand()
#13 /masked-home-path/application/vendor/symfony/console/Application.php(175): Symfony\\Component\\Console\\Application->doRun()
#14 /masked-home-path/application/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
#15 /masked-home-path/application/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#16 {main}
"}
```

### How to reproduce the bug

This happens every time the task is queued using dispatch method 

### Package Version

1.3.0

### PHP Version

8.1

### Laravel Version

10

### CockroachDB Version

23.1.9

**Comment by fresent** [comment]
After looking into this deeply. It's even more baffling.

As the extended chain is 

Illuminate\Database\Connection > Illuminate\Database\PostgresConnection > YlsIdeas\CockroachDb\CockroachDbConnection

And Illuminate\Database\Connection already has this implemented.

**Comment by fresent** [comment]
Things we pull to make things work lol.
Apparently, had a override class to auto retry on select logic for minor exceptions crdb throws, which needed to be ported to laravel 10.

All working as expected now.

**Comment by peterfox** [comment]
my favourite kind of bug, one I don't have to do any work on 😅
